In [2]:
import pandas as pd
import numpy as np
from tableone import TableOne

### Read the datasets

In [3]:

static = pd.read_csv('preprocessing/representations/static.csv')
time_series_2d = pd.read_csv('preprocessing/representations/time_series_2d.csv')
time_series_3d = pd.read_csv('preprocessing/representations/time_series_3d.csv')


folder_sepsis = 'sepsis3_queries/data'
sepsis3 = pd.read_csv(f'{folder_sepsis}/sepsis-df-3.csv')

### Table 1 for time series

In [4]:
time_series_2d = time_series_2d.set_index('icustay_id')
static = static.set_index('icustay_id')

In [5]:
table1_ts = TableOne(time_series_2d,tukey_test=True, normal_test=True)
table1_ts

/Users/maba4574/Desktop/Work/Projects/MIMIC/patient_clustering_EHR/.venv/lib/python3.10/site-packages/pandas/core/indexes/multi.py:643: DeprecationWarning: `cumproduct` is deprecated as of NumPy 1.25.0, and will be removed in NumPy 2.0. Please use `cumprod` instead.
  codes = cartesian_product(codes)
/Users/maba4574/Desktop/Work/Projects/MIMIC/patient_clustering_EHR/.venv/lib/python3.10/site-packages/pandas/core/reshape/util.py:60: DeprecationWarning: `product` is deprecated as of NumPy 1.25.0, and will be removed in NumPy 2.0. Please use `prod` instead.
  return [
/Users/maba4574/Desktop/Work/Projects/MIMIC/patient_clustering_EHR/.venv/lib/python3.10/site-packages/pandas/core/reshape/util.py:60: DeprecationWarning: `product` is deprecated as of NumPy 1.25.0, and will be removed in NumPy 2.0. Please use `prod` instead.
  return [

                                    Missing         Overall
n                                                      5784
hours_in, n (%)                11.5       0    5784 (100.0)
aado2, mean (SD)                       4940   441.2 (133.6)
baseexcess, mean (SD)                  1950      -1.7 (8.4)
bicarbonate, mean (SD)                   13      23.2 (4.5)
totalco2, mean (SD)                    1951      24.4 (5.6)
carboxyhemoglobin, mean (SD)           5596       2.2 (1.5)
chloride, mean (SD)                      13     104.9 (6.2)
calcium, mean (SD)                     3085       1.1 (0.1)
glucose, mean (SD)                        3  164.0 (1461.9)
hematocrit, mean (SD)                    21      32.8 (5.6)
hemoglobin, mean (SD)                    24      11.0 (1.9)
lactate, mean (SD)                     1140       2.3 (1.7)
o2flow, mean (SD)                      5487      8.4 (12.0)
fio2, mean (SD)                        4084     67.4 (22.5)
so2, mean (SD)                         3832     88.7 (11.6)
pco2, mean (SD)                        1951     41.4 (10.2)
peep, mean (SD)                        4470      7.3 (12.7)
ph, mean (SD)                          1771       7.4 (0.1)
po2, mean (SD)                         1951    148.5 (80.8)
potassium, mean (SD)                     13       4.2 (0.6)
requiredo2, mean (SD)                  4940     74.7 (18.4)
sodium, mean (SD)                        13     138.4 (5.1)
temperature, mean (SD)                 3912      36.9 (1.3)
tidalvolume, mean (SD)                 4395    503.3 (99.4)
spo2, mean (SD)                           7      96.9 (2.3)
heartrate, mean (SD)                      4     87.1 (16.6)
sysbp, mean (SD)                         11    117.3 (16.2)
diasbp, mean (SD)                        11     61.3 (10.5)
meanbp, mean (SD)                         4     76.5 (10.6)
resprate, mean (SD)                       6      19.7 (4.3)
tempc, mean (SD)                        107      36.8 (0.7)
aniongap, mean (SD)                      25      14.5 (3.7)
albumin, mean (SD)                     2858       3.1 (0.7)
bands, mean (SD)                       4673       9.7 (9.6)
bilirubin, mean (SD)                   2141       2.0 (4.0)
creatinine, mean (SD)                    16       1.5 (1.5)
platelet, mean (SD)                      27   217.2 (116.5)
ptt, mean (SD)                          427     35.7 (16.4)
inr, mean (SD)                          404       1.5 (0.9)
pt, mean (SD)                           404      16.6 (7.4)
bun, mean (SD)                           17     28.9 (22.9)
wbc, mean (SD)                           26     12.7 (10.8)
dopamine_dose, mean (SD)               5499     73.2 (80.8)
vasopressin_dose, mean (SD)            5531     35.1 (32.2)
phenylephrine_dose, mean (SD)          4809      9.4 (14.9)
epinephrine_dose, mean (SD)            5676       0.6 (0.7)
norepinephrine_dose, mean (SD)         4706       1.4 (1.7)
urineoutput, mean (SD)                   71   138.2 (147.8)
[1] Normality test reports non-normal
                                  distributions for: aado2, baseexcess, bicarbonate, totalco2, carboxyhemoglobin, chloride, calcium, glucose, hematocrit, hemoglobin, lactate, o2flow, fio2, so2, pco2, peep, ph, po2, potassium, requiredo2, sodium, temperature, tidalvolume, spo2, heartrate, sysbp, diasbp, meanbp, resprate, tempc, aniongap, bands, bilirubin, creatinine, platelet, ptt, inr, pt, bun, wbc, dopamine_dose, vasopressin_dose, phenylephrine_dose, epinephrine_dose, norepinephrine_dose, urineoutput.
[2] Tukey test indicates far outliers
                                  in: baseexcess, bicarbonate, totalco2, chloride, calcium, glucose, lactate, o2flow, so2, pco2, peep, ph, po2, potassium, sodium, temperature, tidalvolume, spo2, meanbp, resprate, tempc, aniongap, bands, bilirubin, creatinine, platelet, ptt, inr, pt, bun, wbc, dopamine_dose, phenylephrine_dose, epinephrine_dose, norepinephrine_dose, urineoutput.

### Table 1 for static

In [6]:
table1_st = TableOne(static ,tukey_test=True, normal_test=True,display_all=True)
table1_st

                                               Missing      Overall
n                                                              5784
vent, n (%)                              0           0  3002 (51.9)
                                         1              2782 (48.1)
congestive_heart_failure, n (%)          0           0  5645 (97.6)
                                         1                139 (2.4)
cardiac_arrhythmias, n (%)               0           0  5750 (99.4)
                                         1                 34 (0.6)
valvular_disease, n (%)                  0           0  5714 (98.8)
                                         1                 70 (1.2)
pulmonary_circulation, n (%)             0           0  5739 (99.2)
                                         1                 45 (0.8)
peripheral_vascular, n (%)               0           0  5740 (99.2)
                                         1                 44 (0.8)
hypertension, n (%)                      0           0  5757 (99.5)
                                         1                 27 (0.5)
other_neurological, n (%)                0           0  5715 (98.8)
                                         1                 69 (1.2)
chronic_pulmonary, n (%)                 0           0  5724 (99.0)
                                         1                 60 (1.0)
diabetes_uncomplicated, n (%)            0           0  5748 (99.4)
                                         1                 36 (0.6)
diabetes_complicated, n (%)              0           0  5763 (99.6)
                                         1                 21 (0.4)
renal_failure, n (%)                     0           0  5763 (99.6)
                                         1                 21 (0.4)
liver_disease, n (%)                     0           0  5683 (98.3)
                                         1                101 (1.7)
aids, n (%)                              0           0  5767 (99.7)
                                         1                 17 (0.3)
lymphoma, n (%)                          0           0  5759 (99.6)
                                         1                 25 (0.4)
metastatic_cancer, n (%)                 0           0  5676 (98.1)
                                         1                108 (1.9)
solid_tumor, n (%)                       0           0  5579 (96.5)
                                         1                205 (3.5)
obesity, n (%)                           0           0  5777 (99.9)
                                         1                  7 (0.1)
fluid_electrolyte, n (%)                 0           0  5760 (99.6)
                                         1                 24 (0.4)
alcohol_abuse, n (%)                     0           0  5761 (99.6)
                                         1                 23 (0.4)
F, n (%)                                 False       0  3221 (55.7)
                                         True           2563 (44.3)
M, n (%)                                 False       0  2563 (44.3)
                                         True           3221 (55.7)
adults, n (%)                            False       0  3407 (58.9)
                                         True           2377 (41.1)
seniors, n (%)                           False       0  2531 (43.8)
                                         True           3253 (56.2)
youth, n (%)                             False       0  5630 (97.3)
                                         True             154 (2.7)
race_white, n (%)                        0           0  1582 (27.4)
                                         1              4202 (72.6)
race_black, n (%)                        0           0  5281 (91.3)
                                         1                503 (8.7)
race_hispanic, n (%)                     0           0  5596 (96.7)
                                         1                188 (3.3)
race_other, n (%)                        0           0  4893 (84.6)
                                         1               891 (15.4)
gcs_13_15, n (%)                         False       0  2585 (44.7)
                                         True           3199 (55.3)
gcs_9_12, n (%)                          False       0  4838 (83.6)
                                         True            946 (16.4)
gcs_<8, n (%)                            False       0  4145 (71.7)
                                         True           1639 (28.3)
diabetes, n (%)                          0           0  5727 (99.0)
                                         1                 57 (1.0)
circulatory, n (%)                       0           0  5566 (96.2)
                                         1                218 (3.8)
circulatory_infectious_congenital, n (%) 0           0  5670 (98.0)
                                         1                114 (2.0)
nervous_and_sense, n (%)                 0           0  5714 (98.8)
                                         1                 70 (1.2)
endocrinal_nutritional, n (%)            0           0  5693 (98.4)
                                         1                 91 (1.6)
neoplasms, n (%)                         0           0  5446 (94.2)
                                         1                338 (5.8)
blood_and_blood_forming, n (%)           0           0  5778 (99.9)
                                         1                  6 (0.1)

### Table 1 for sepsis3

In [7]:
sepsis3.columns

Index(['icustay_id', 'hadm_id', 'excluded', 'intime', 'outtime', 'dbsource',
       'suspected_infection_time_poe', 'suspected_infection_time_poe_days',
       'specimen_poe', 'positiveculture_poe', 'antibiotic_time_poe',
       'blood_culture_time', 'blood_culture_positive', 'age', 'gender',
       'is_male', 'ethnicity', 'race_white', 'race_black', 'race_hispanic',
       'race_other', 'metastatic_cancer', 'diabetes', 'height', 'weight',
       'bmi', 'first_service', 'hospital_expire_flag', 'thirtyday_expire_flag',
       'icu_los', 'hosp_los', 'sepsis_angus', 'sepsis_martin',
       'sepsis_explicit', 'septic_shock_explicit', 'severe_sepsis_explicit',
       'sepsis_nqf', 'sepsis_cdc', 'sepsis_cdc_simple', 'elixhauser_hospital',
       'vent', 'sofa', 'lods', 'sirs', 'qsofa', 'qsofa_sysbp_score',
       'qsofa_gcs_score', 'qsofa_resprate_score', 'composite_outcome',
       'blood culture', 'suspicion_poe', 'abx_poe', 'sepsis-3', 'sofa>=2'],
      dtype='object')

In [8]:
sepsis3temp1 = sepsis3[['dbsource', 'age', 'gender',
       'race_white', 'race_black', 'race_hispanic',
       'race_other',  'height', 'weight',
       'bmi','hospital_expire_flag', 'thirtyday_expire_flag',
       'icu_los', 'hosp_los', 'first_service']]

In [14]:
sepsis3temp2 = sepsis3[[ 'sepsis_angus', 'sepsis_martin',
       'sepsis_explicit', 'septic_shock_explicit', 'severe_sepsis_explicit',
       'elixhauser_hospital', 'sepsis_cdc', 'sepsis_cdc_simple',
       'vent', 'sirs', 'qsofa', 'qsofa_sysbp_score',
       'qsofa_gcs_score', 'qsofa_resprate_score', 'suspicion_poe']]

In [ ]:
table1_sepsis3 = TableOne(sepsis3temp1, missing=False, tukey_test=True, normal_test=True,display_all=True)
table1_sepsis3

/Users/maba4574/Desktop/Work/Projects/MIMIC/patient_clustering_EHR/.venv/lib/python3.10/site-packages/pandas/core/indexes/multi.py:643: DeprecationWarning: `cumproduct` is deprecated as of NumPy 1.25.0, and will be removed in NumPy 2.0. Please use `cumprod` instead.
  codes = cartesian_product(codes)
/Users/maba4574/Desktop/Work/Projects/MIMIC/patient_clustering_EHR/.venv/lib/python3.10/site-packages/pandas/core/reshape/util.py:60: DeprecationWarning: `product` is deprecated as of NumPy 1.25.0, and will be removed in NumPy 2.0. Please use `prod` instead.
  return [
/Users/maba4574/Desktop/Work/Projects/MIMIC/patient_clustering_EHR/.venv/lib/python3.10/site-packages/pandas/core/reshape/util.py:60: DeprecationWarning: `product` is deprecated as of NumPy 1.25.0, and will be removed in NumPy 2.0. Please use `prod` instead.
  return [

                                              Overall
n                                                5784
dbsource, n (%)              metavision  5784 (100.0)
age, mean (SD)                            65.5 (17.6)
gender, n (%)                F            2563 (44.3)
                             M            3221 (55.7)
race_white, n (%)            0            1582 (27.4)
                             1            4202 (72.6)
race_black, n (%)            0            5281 (91.3)
                             1              503 (8.7)
race_hispanic, n (%)         0            5596 (96.7)
                             1              188 (3.3)
race_other, n (%)            0            4893 (84.6)
                             1             891 (15.4)
height, mean (SD)                        169.6 (10.9)
weight, mean (SD)                         81.4 (27.3)
bmi, mean (SD)                             28.8 (7.5)
hospital_expire_flag, n (%)  0            4948 (85.5)
                             1             836 (14.5)
thirtyday_expire_flag, n (%) 0            4743 (82.0)
                             1            1041 (18.0)
icu_los, mean (SD)                          4.7 (6.1)
hosp_los, mean (SD)                        10.3 (9.9)
first_service, n (%)         CMED          720 (12.4)
                             ENT             20 (0.3)
                             GU              48 (0.8)
                             GYN             18 (0.3)
                             MED          3155 (54.5)
                             NMED           235 (4.1)
                             NSURG          440 (7.6)
                             OBS             10 (0.2)
                             OMED            97 (1.7)
                             ORTHO          119 (2.1)
                             PSURG           11 (0.2)
                             SURG           562 (9.7)
                             TRAUM          349 (6.0)
[1] Normality test reports non-normal
                                  distributions for: age, height, weight, bmi, icu_los, hosp_los.
[2] Tukey test indicates far outliers
                                  in: weight, bmi, icu_los, hosp_los.

/Users/maba4574/Desktop/Work/Projects/MIMIC/patient_clustering_EHR/.venv/lib/python3.10/site-packages/pandas/core/indexes/multi.py:643: DeprecationWarning: `cumproduct` is deprecated as of NumPy 1.25.0, and will be removed in NumPy 2.0. Please use `cumprod` instead.
  codes = cartesian_product(codes)
/Users/maba4574/Desktop/Work/Projects/MIMIC/patient_clustering_EHR/.venv/lib/python3.10/site-packages/pandas/core/reshape/util.py:60: DeprecationWarning: `product` is deprecated as of NumPy 1.25.0, and will be removed in NumPy 2.0. Please use `prod` instead.
  return [
/Users/maba4574/Desktop/Work/Projects/MIMIC/patient_clustering_EHR/.venv/lib/python3.10/site-packages/pandas/core/reshape/util.py:60: DeprecationWarning: `product` is deprecated as of NumPy 1.25.0, and will be removed in NumPy 2.0. Please use `prod` instead.
  return [

                                              Overall
n                                                5784
dbsource, n (%)              metavision  5784 (100.0)
age, mean (SD)                            65.5 (17.6)
gender, n (%)                F            2563 (44.3)
                             M            3221 (55.7)
race_white, n (%)            0            1582 (27.4)
                             1            4202 (72.6)
race_black, n (%)            0            5281 (91.3)
                             1              503 (8.7)
race_hispanic, n (%)         0            5596 (96.7)
                             1              188 (3.3)
race_other, n (%)            0            4893 (84.6)
                             1             891 (15.4)
height, mean (SD)                        169.6 (10.9)
weight, mean (SD)                         81.4 (27.3)
bmi, mean (SD)                             28.8 (7.5)
hospital_expire_flag, n (%)  0            4948 (85.5)
                             1             836 (14.5)
thirtyday_expire_flag, n (%) 0            4743 (82.0)
                             1            1041 (18.0)
icu_los, mean (SD)                          4.7 (6.1)
hosp_los, mean (SD)                        10.3 (9.9)
first_service, n (%)         CMED          720 (12.4)
                             ENT             20 (0.3)
                             GU              48 (0.8)
                             GYN             18 (0.3)
                             MED          3155 (54.5)
                             NMED           235 (4.1)
                             NSURG          440 (7.6)
                             OBS             10 (0.2)
                             OMED            97 (1.7)
                             ORTHO          119 (2.1)
                             PSURG           11 (0.2)
                             SURG           562 (9.7)
                             TRAUM          349 (6.0)
[1] Normality test reports non-normal
                                  distributions for: age, height, weight, bmi, icu_los, hosp_los.
[2] Tukey test indicates far outliers
                                  in: weight, bmi, icu_los, hosp_los.

In [ ]:
print(table1_sepsis3.tabulate(tablefmt = "latex"))

\begin{tabular}{lll}
\hline
                              &            & Overall      \\
\hline
 n                            &            & 5784         \\
 dbsource, n (\%)              & metavision & 5784 (100.0) \\
 age, mean (SD)               &            & 65.5 (17.6)  \\
 gender, n (\%)                & F          & 2563 (44.3)  \\
                              & M          & 3221 (55.7)  \\
 race\_white, n (\%)            & 0          & 1582 (27.4)  \\
                              & 1          & 4202 (72.6)  \\
 race\_black, n (\%)            & 0          & 5281 (91.3)  \\
                              & 1          & 503 (8.7)    \\
 race\_hispanic, n (\%)         & 0          & 5596 (96.7)  \\
                              & 1          & 188 (3.3)    \\
 race\_other, n (\%)            & 0          & 4893 (84.6)  \\
                              & 1          & 891 (15.4)   \\
 height, mean (SD)            &            & 169.6 (10.9) \\
 weight, mean (SD)            &            & 81.4 (27.3)  \\
 bmi, mean (SD)               &            & 28.8 (7.5)   \\
 hospital\_expire\_flag, n (\%)  & 0          & 4948 (85.5)  \\
                              & 1          & 836 (14.5)   \\
 thirtyday\_expire\_flag, n (\%) & 0          & 4743 (82.0)  \\
                              & 1          & 1041 (18.0)  \\
 icu\_los, mean (SD)           &            & 4.7 (6.1)    \\
 hosp\_los, mean (SD)          &            & 10.3 (9.9)   \\
 first\_service, n (\%)         & CMED       & 720 (12.4)   \\
                              & ENT        & 20 (0.3)     \\
                              & GU         & 48 (0.8)     \\
                              & GYN        & 18 (0.3)     \\
                              & MED        & 3155 (54.5)  \\
                              & NMED       & 235 (4.1)    \\
                              & NSURG      & 440 (7.6)    \\
                              & OBS        & 10 (0.2)     \\
                              & OMED       & 97 (1.7)     \\
                              & ORTHO      & 119 (2.1)    \\
                              & PSURG      & 11 (0.2)     \\
                              & SURG       & 562 (9.7)    \\
                              & TRAUM      & 349 (6.0)    \\
\hline
\end{tabular}

In [ ]:
table1_sepsis3_2 = TableOne(sepsis3temp2, missing=False, tukey_test=True, normal_test=True,display_all=True)
table1_sepsis3_2

                                       Overall
n                                         5784
sepsis_angus, n (%)           0    2917 (50.4)
                              1    2867 (49.6)
sepsis_martin, n (%)          0    4210 (72.8)
                              1    1574 (27.2)
sepsis_explicit, n (%)        0    4776 (82.6)
                              1    1008 (17.4)
septic_shock_explicit, n (%)  0    5044 (87.2)
                              1     740 (12.8)
severe_sepsis_explicit, n (%) 0    4777 (82.6)
                              1    1007 (17.4)
elixhauser_hospital, n (%)    -1       6 (0.1)
                              -3       2 (0.0)
                              -4      15 (0.3)
                              -9       2 (0.0)
                              0    5631 (97.4)
                              2        1 (0.0)
                              4       46 (0.8)
                              6        2 (0.0)
                              7        6 (0.1)
                              9       73 (1.3)
sepsis_cdc, n (%)             0    2263 (39.1)
                              1    3521 (60.9)
sepsis_cdc_simple, n (%)      0    2778 (48.0)
                              1    3006 (52.0)
vent, n (%)                   0    3002 (51.9)
                              1    2782 (48.1)
sirs, n (%)                   0       39 (0.7)
                              1      414 (7.2)
                              2    1285 (22.2)
                              3    2318 (40.1)
                              4    1728 (29.9)
qsofa, n (%)                  0      143 (2.5)
                              1    1291 (22.3)
                              2    3318 (57.4)
                              3    1032 (17.8)
qsofa_sysbp_score, n (%)      0.0  1387 (24.0)
                              1.0  4386 (76.0)
qsofa_gcs_score, n (%)        0.0  4148 (71.8)
                              1.0  1629 (28.2)
qsofa_resprate_score, n (%)   0.0   770 (13.3)
                              1.0  5008 (86.7)

                                         Overall
n                                           5784
sepsis_angus, n (%)           0      2917 (50.4)
                              1      2867 (49.6)
sepsis_martin, n (%)          0      4210 (72.8)
                              1      1574 (27.2)
sepsis_explicit, n (%)        0      4776 (82.6)
                              1      1008 (17.4)
septic_shock_explicit, n (%)  0      5044 (87.2)
                              1       740 (12.8)
severe_sepsis_explicit, n (%) 0      4777 (82.6)
                              1      1007 (17.4)
elixhauser_hospital, n (%)    -1         6 (0.1)
                              -3         2 (0.0)
                              -4        15 (0.3)
                              -9         2 (0.0)
                              0      5631 (97.4)
                              2          1 (0.0)
                              4         46 (0.8)
                              6          2 (0.0)
                              7          6 (0.1)
                              9         73 (1.3)
sepsis_cdc, n (%)             0      2263 (39.1)
                              1      3521 (60.9)
sepsis_cdc_simple, n (%)      0      2778 (48.0)
                              1      3006 (52.0)
vent, n (%)                   0      3002 (51.9)
                              1      2782 (48.1)
sirs, n (%)                   0         39 (0.7)
                              1        414 (7.2)
                              2      1285 (22.2)
                              3      2318 (40.1)
                              4      1728 (29.9)
qsofa, n (%)                  0        143 (2.5)
                              1      1291 (22.3)
                              2      3318 (57.4)
                              3      1032 (17.8)
qsofa_sysbp_score, n (%)      0.0    1387 (24.0)
                              1.0    4386 (76.0)
qsofa_gcs_score, n (%)        0.0    4148 (71.8)
                              1.0    1629 (28.2)
qsofa_resprate_score, n (%)   0.0     770 (13.3)
                              1.0    5008 (86.7)
suspicion_poe, n (%)          True  5784 (100.0)

In [ ]:
print(table1_sepsis3_2.tabulate(tablefmt = "latex"))

\begin{tabular}{lll}
\hline
                               &     & Overall     \\
\hline
 n                             &     & 5784        \\
 sepsis\_angus, n (\%)           & 0   & 2917 (50.4) \\
                               & 1   & 2867 (49.6) \\
 sepsis\_martin, n (\%)          & 0   & 4210 (72.8) \\
                               & 1   & 1574 (27.2) \\
 sepsis\_explicit, n (\%)        & 0   & 4776 (82.6) \\
                               & 1   & 1008 (17.4) \\
 septic\_shock\_explicit, n (\%)  & 0   & 5044 (87.2) \\
                               & 1   & 740 (12.8)  \\
 severe\_sepsis\_explicit, n (\%) & 0   & 4777 (82.6) \\
                               & 1   & 1007 (17.4) \\
 elixhauser\_hospital, n (\%)    & -1  & 6 (0.1)     \\
                               & -3  & 2 (0.0)     \\
                               & -4  & 15 (0.3)    \\
                               & -9  & 2 (0.0)     \\
                               & 0   & 5631 (97.4) \\
                               & 2   & 1 (0.0)     \\
                               & 4   & 46 (0.8)    \\
                               & 6   & 2 (0.0)     \\
                               & 7   & 6 (0.1)     \\
                               & 9   & 73 (1.3)    \\
 sepsis\_cdc, n (\%)             & 0   & 2263 (39.1) \\
                               & 1   & 3521 (60.9) \\
 sepsis\_cdc\_simple, n (\%)      & 0   & 2778 (48.0) \\
                               & 1   & 3006 (52.0) \\
 vent, n (\%)                   & 0   & 3002 (51.9) \\
                               & 1   & 2782 (48.1) \\
 sirs, n (\%)                   & 0   & 39 (0.7)    \\
                               & 1   & 414 (7.2)   \\
                               & 2   & 1285 (22.2) \\
                               & 3   & 2318 (40.1) \\
                               & 4   & 1728 (29.9) \\
 qsofa, n (\%)                  & 0   & 143 (2.5)   \\
                               & 1   & 1291 (22.3) \\
                               & 2   & 3318 (57.4) \\
                               & 3   & 1032 (17.8) \\
 qsofa\_sysbp\_score, n (\%)      & 0.0 & 1387 (24.0) \\
                               & 1.0 & 4386 (76.0) \\
 qsofa\_gcs\_score, n (\%)        & 0.0 & 4148 (71.8) \\
                               & 1.0 & 1629 (28.2) \\
 qsofa\_resprate\_score, n (\%)   & 0.0 & 770 (13.3)  \\
                               & 1.0 & 5008 (86.7) \\
\hline
\end{tabular}